In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from scipy.stats import chisquare,chi2_contingency

In [14]:
ob=np.array([410,340,250,95,85,70])
ex=np.array([404,340,256,101,85,64])


pandas.core.series.Series

In [15]:
chi_val=(((ob-ex)**2)/ex).sum()

In [25]:
#by using built-in Library
#represent your cross tab (observed count)
CT=pd.DataFrame(np.array([[410,340,250],[95,85,70]]))
CT.columns=['Healthy','Mild','Severe']
CT.index=['Sc-1','Sc-2']
CT
                

Healthy  Mild  Severe
Sc-1      410   340     250
Sc-2       95    85      70

In [27]:
ch_val,p_val,nrow,EC=chi2_contingency(CT)

In [28]:
print(EC)

[[404. 340. 256.]
 [101.  85.  64.]]


In [30]:
print(ch_val)

1.1486695544554455


In [31]:
print(p_val)

0.5630793174318253


In [ ]:
#Inference: p-val>0.05, which implies, we fail to reject the H0: Proportion of samples across the
#three groups (healthy,mild & Severe ) is significantly different

In [34]:
A=pd.read_table('HR.txt',index_col=0)
A.head()

Attrition  Age  BusinessTravel  DailyRate  Department  \
Individual                                                          
Ind1              Yes   41               1       1102           1   
Ind2               No   49               2        279           2   
Ind3              Yes   37               1       1373           2   
Ind4               No   33               2       1392           2   
Ind5               No   27               1        591           2   

             DistanceFromHome  Education  EducationField  EmployeeCount  \
Individual                                                                
Ind1                        1          2               1              1   
Ind2                        8          1               1              1   
Ind3                        2          2               6              1   
Ind4                        3          4               1              1   
Ind5                        2          1               2              1   

             EmployeeNumber          ...           RelationshipSatisfaction  \
Individual                           ...                                      
Ind1                      1          ...                                  1   
Ind2                      2          ...                                  4   
Ind3                      4          ...                                  2   
Ind4                      5          ...                                  3   
Ind5                      7          ...                                  4   

             StandardHours  StockOptionLevel  TotalWorkingYears  \
Individual                                                        
Ind1                    80                 0                  8   
Ind2                    80                 1                 10   
Ind3                    80                 0                  7   
Ind4                    80                 0                  8   
Ind5                    80                 1                  6   

             TrainingTimesLastYear  WorkLifeBalance  YearsAtCompany  \
Individual                                                            
Ind1                             0                1               6   
Ind2                             3                3              10   
Ind3                             3                3               0   
Ind4                             3                3               8   
Ind5                             3                3               2   

             YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
Individual                                                                      
Ind1                          4                        0                     5  
Ind2                          7                        1                     7  
Ind3                          0                        0                     0  
Ind4                          7                        3                     0  
Ind5                          2                        2                     2  

[5 rows x 34 columns]

In [35]:
A['Department'].value_counts()

2    961
1    446
3     63
Name: Department, dtype: int64

In [36]:
T=pd.crosstab(A['Attrition'],A['Department'])
T

Department    1    2   3
Attrition               
No          354  828  51
Yes          92  133  12

In [37]:
chi2_contingency(T)

(10.79600732241067,
 0.004525606574479633,
 2,
 array([[374.09387755, 806.06326531,  52.84285714],
        [ 71.90612245, 154.93673469,  10.15714286]]))

In [38]:
chisquare(A['Department'].value_counts())

Power_divergenceResult(statistic=828.7877551020408, pvalue=1.074052833315366e-180)

In [39]:
A['Department'].value_counts()

2    961
1    446
3     63
Name: Department, dtype: int64